### ISSUE TITLE
REST API

### ISSUE THREAD

**Issue by matlafluxs** [BambooMachine/MicroFW#3]
Any plans for API? Something Like http://www.slimframework.com/, it could be cool.

**Comment by radimsuckr** [comment]
You mean support for REST APIs? Our current target is usable release with tests coverage. REST API may be next milestone.

You can fork this repository and contribute with us. :)

**Comment by polarkac** [comment]
6dfdfeb commit introduce class based view where you can allow only certain HTTP methods. 

Class based view has advantage that method is called based on HTTP method (post - $class->POST(), DELETE, $class->DELETE()). This should provide some basic options for REST API.

**Comment by matlafluxs** [comment]
Thanks, it was thought for a future milestone. @polarkac Thanks!

**Comment by polarkac** [comment]
**Just correction of myself. With view I meant controller.**

I planned this (class based controller) from start. You dont have to use class based controller. Function controller has access to request where you can get HTTP method, so you can create logic around that.

Also @Grelek created demo application and I just pushed examples of class based controllers. https://github.com/BambooMachine/MicroFW-demoapp
